<a href="https://colab.research.google.com/github/GARVNAIN19/dsa-journey/blob/main/ml/day01_numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)
print("ML journey started! 🚀")

NumPy version: 2.0.2
Pandas version: 2.2.2
ML journey started! 🚀


In [ ]:
# Like a super powerful calculator
nums = np.array([1, 2, 3, 4, 5])
print(nums * 2)  # → [2, 4, 6, 8, 10]

[ 2  4  6  8 10]


In [ ]:
# Like a spreadsheet
data = {'Name': ['Garv', 'Alex'], 'Age': [20, 22]}
df = pd.DataFrame(data)
print(df)

   Name  Age
0  Garv   20
1  Alex   22


In [ ]:
import numpy as np

# Create an array
nums = np.array([10, 20, 30, 40, 50])

print(nums)           # the array
print(nums.mean())    # average
print(nums.max())     # biggest
print(nums.min())     # smallest
print(nums * 2)       # multiply everything by 2

[10 20 30 40 50]
30.0
50
10
[ 20  40  60  80 100]


In [4]:
import pandas as pd

# Create a simple table
data = {
    'Name':   ['Garv', 'Alex', 'Sara', 'John'],
    'Age':    [20,     22,     21,     23],
    'Score':  [85,     90,     78,     95]
}

df = pd.DataFrame(data)
print(df)
print("---")
print("Average score:", df['Score'].mean())
print("Highest score:", df['Score'].max())


   Name  Age  Score
0  Garv   20     85
1  Alex   22     90
2  Sara   21     78
3  John   23     95
---
Average score: 87.0
Highest score: 95


In [5]:
import pandas as pd

# Load Titanic dataset directly from internet
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# See first 5 rows
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [6]:
# How many rows and columns?
print("Shape:", df.shape)

# Basic statistics
print(df.describe())

# How many survived?
print("\nSurvived counts:")
print(df['Survived'].value_counts())

# Any missing data?
print("\nMissing values:")
print(df.isnull().sum())

Shape: (891, 12)
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200  

Survived counts:
Survived
0    549
1    342
Name: count, dtype:

In [4]:
# Fill missing Age with average age
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Fill missing Embarked with most common value
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# Drop Cabin column (too many missing)
df = df.drop('Cabin', axis=1)

# Check missing values again
print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64


In [7]:
# Survival rate by gender
print("Survival by gender:")
print(df.groupby('Sex')['Survived'].mean())

# Survival rate by class
print("\nSurvival by class:")
print(df.groupby('Pclass')['Survived'].mean())

Survival by gender:
Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

Survival by class:
Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64
